import json, os
NL = chr(10)
BT = chr(96)
BT3 = chr(96)*3
DR = os.path.dirname(os.path.abspath(__file__))
NP = os.path.join(DR, "guia_06.ipynb")
with open(NP, encoding="utf-8") as fh: nb = json.load(fh)
cs = nb["cells"]
def ss(i, t):
    ln = t.split(NL)
    cs[i]["source"] = [l+NL for l in ln[:-1]] + [ln[-1]]
    print(f"Cell {i} set")
cd = {}
cd[0] = NL.join([
"# Guia 06: Clases, Excepciones y Modulos",
"",
"> **Autor:** Francisco Alvarez Varas | EDEM MDA 2025/2026",
"",
"| Dificultad | Ejercicios | Temas principales |",
"|:----------:|:----------:|:------------------|",
"| Intermedia-Avanzada | 9 | OOP, Excepciones, Modulos, Herencia, Decoradores |",
"",
"**Fuentes:** MIT 6.0001 (OOP), Harvard CS50P (decoradores), Clases EDEM",
"",
"**Instrucciones:**",
"- Escribe tu codigo en las celdas marcadas con "+BT+"# TU CODIGO AQUI"+BT,
"- Ejecuta la celda con **Shift + Enter**",
"- Consulta la solucion desplegable cuando lo necesites",
"","---","",
"### Tabla de Contenidos","",
"| # | Ejercicio | Seccion |",
"|:-:|:----------|:--------|",
"| 1 | CuentaBancaria (tu primera clase) | Clases (OOP) |",
"| 2 | Clase Alumno (mas metodos) | Clases (OOP) |",
"| 3 | Division segura (try/except) | Excepciones |",
"| 4 | Multiples errores | Excepciones |",
"| 5 | Lectura de archivos | Archivos y Modulos |",
"| 6 | API publica con requests | Archivos y Modulos |",
"| 7 | Clase Producto (juntando todo) | OOP + Excepciones |",
"| 8 | Sistema de vehiculos (herencia) | Herencia |",
"| 9 | Decorador medir_tiempo | Decoradores |",
])
cd[1] = NL.join([
"---","",
"## Seccion 1: Clases - Programacion Orientada a Objetos (OOP)","",
"Las **clases** permiten crear tus propios tipos de datos agrupando:",
"- **Atributos**: datos que pertenecen al objeto",
"- **Metodos**: funciones que operan sobre esos datos","",
"> **Recuerda:**",
"> "+BT3+"python",
"> class NombreClase:",
">     def __init__(self, parametros):",
">         self.atributo = valor",
">",
">     def metodo(self):",
">         # codigo que usa self.atributo",
"> "+BT3,
">",
"> - "+BT+"__init__"+BT+" es el **constructor**: se ejecuta al crear un objeto",
"> - "+BT+"self"+BT+" es una referencia al propio objeto (siempre primer parametro, pero NO lo pasas al llamar)",
"> - **Crear objeto**: "+BT+"variable = NombreClase(argumentos)"+BT,
"> - **Usar metodo**: "+BT+"variable.metodo()"+BT,
"> - **Leer atributo**: "+BT+"variable.atributo"+BT,
])
cd[2] = NL.join([
"---","",
"## Ejercicio 1 de 9: Tu primera clase - CuentaBancaria","",
"> **Conceptos clave:** "+BT+"class"+BT+", "+BT+"__init__"+BT+", "+BT+"self"+BT+", metodos, atributos","",
"Crea una clase "+BT+"CuentaBancaria"+BT+" con:","",
"**Atributos** (en "+BT+"__init__"+BT+"):",
"- "+BT+"titular"+BT+" (string)",
"- "+BT+"saldo"+BT+" (float)","",
"**Metodos:**",
"- "+BT+"depositar(cantidad)"+BT+": suma la cantidad al saldo. Si cantidad <= 0, imprime "+BT+'"Cantidad no valida"'+BT,
"- "+BT+"mostrar()"+BT+": devuelve un string: "+BT+'"Titular: X | Saldo: Y euros"'+BT,
"","**Luego:**",
"1. Crea una cuenta para ti con saldo 100",
"2. Deposita 50",
"3. Intenta depositar -20 (debe dar error)",
"4. Muestra el estado de la cuenta",
"","### Tu turno",
])
cd[6] = NL.join([
"---","",
"## Ejercicio 2 de 9: Clase con mas metodos - Alumno","",
"> **Conceptos clave:** listas como atributos, validacion en metodos, "+BT+"len()"+BT+", "+BT+"sum()"+BT+", "+BT+"max()"+BT,"",
"Crea una clase "+BT+"Alumno"+BT+" con:","",
"**Atributos:**",
"- "+BT+"nombre"+BT+" (string)",
"- "+BT+"notas"+BT+" (lista vacia al principio)","",
"**Metodos:**",
"- "+BT+"agregar_nota(nota)"+BT+": agrega una nota a la lista. Solo acepta notas entre 0 y 10",
"- "+BT+"promedio()"+BT+": devuelve el promedio de las notas. Si no hay notas, devuelve 0",
"- "+BT+"mejor_nota()"+BT+": devuelve la nota mas alta",
"- "+BT+"mostrar()"+BT+": imprime nombre, notas y promedio","",
"**Luego:**",
"1. Crea un alumno",
"2. Agrega 5 notas",
"3. Muestra su informacion",
"","### Tu turno",
])
cd[10] = NL.join([
"---","",
"## Seccion 2: Excepciones - Manejo de errores con try/except","",
"Las **excepciones** permiten manejar errores sin que el programa se detenga.","",
"> **Recuerda:**",
"> "+BT3+"python",
"> try:",
">     # codigo que PUEDE fallar",
"> except TipoError:",
">     # que hacer si falla con ese error",
"> except OtroError:",
">     # que hacer si falla con otro error",
"> else:",
">     # codigo si NO hubo error (opcional)",
"> finally:",
">     # codigo que se ejecuta SIEMPRE (opcional)",
"> "+BT3,"",
"**Errores comunes en Python:**","",
"| Error | Causa |",
"|-------|-------|",
"| "+BT+"ZeroDivisionError"+BT+" | Division por cero |",
"| "+BT+"ValueError"+BT+" | Valor incorrecto |",
"| "+BT+"TypeError"+BT+" | Tipo incorrecto |",
"| "+BT+"KeyError"+BT+" | Clave no existe en diccionario |",
"| "+BT+"IndexError"+BT+" | Indice fuera de rango en lista |",
"| "+BT+"FileNotFoundError"+BT+" | Archivo no encontrado |",
"| "+BT+"NameError"+BT+" | Variable no definida |",
])
cd[11] = NL.join([
"---","",
"## Ejercicio 3 de 9: Try/Except - Division segura","",
"> **Conceptos clave:** "+BT+"try"+BT+", "+BT+"except"+BT+", "+BT+"ZeroDivisionError"+BT,"",
"Crea un programa que:",
"1. Defina dos numeros ("+BT+"numerador"+BT+" y "+BT+"denominador"+BT+")",
"2. Intente dividir el primero entre el segundo",
"3. Si hay division por cero, imprima un mensaje de error",
"4. Si todo va bien, imprima el resultado","",
"> **Tip:** "+BT+"ZeroDivisionError"+BT+" es el error que lanza Python al dividir por cero.","",
"### Tu turno",
])
cd[15] = NL.join([
"---","",
"## Ejercicio 4 de 9: Try/Except multiples errores","",
"> **Conceptos clave:** multiples "+BT+"except"+BT+", "+BT+"ValueError"+BT+", "+BT+"ZeroDivisionError"+BT+", "+BT+"float()"+BT,"",
"Crea una funcion "+BT+"division_segura"+BT+" que reciba dos valores (pueden ser strings o numeros) y:",
"1. Intente convertirlos a "+BT+"float"+BT,
"2. Intente dividirlos",
"3. Capture "+BT+"ValueError"+BT+" si no se pueden convertir",
"4. Capture "+BT+"ZeroDivisionError"+BT+" si se divide por cero",
"5. Devuelva el resultado o "+BT+"None"+BT+" si hay error","",
"**Pruebas:**",
BT3+"python",
"print(division_segura(10, 3))       # 3.333...",
"print(division_segura(10, 0))       # Error division por cero",
'"print(division_segura('+chr(39)+chr(39)+'abc'+chr(39)+chr(39)+', 3))    # Error conversion",'
BT3,"",
"### Tu turno",
])
cd[19] = NL.join([
"---","",
"## Seccion 3: Archivos y Modulos","",
"### Lectura/escritura de archivos","",
"> **Recuerda:**",
"> "+BT3+"python",
"> with open("archivo.txt", "w", encoding="utf-8") as f:",
">     f.write("contenido")",
"> "+BT3,
">",
"> - "+BT+"with"+BT+" se encarga de **cerrar el archivo automaticamente**",
"> - Modos: "+BT+"r"+BT+" = leer, "+BT+"w"+BT+" = escribir, "+BT+"a"+BT+" = agregar al final",
"> - "+BT+"encoding="utf-8""+BT+" para caracteres especiales",
"> - "+BT+".strip()"+BT+" quita espacios y saltos de linea de los extremos","",
"### Modulos","",
"Los **modulos** son archivos con codigo reutilizable.","",
"- "+BT+"import modulo"+BT+" -> importa todo el modulo",
"- "+BT+"from modulo import algo"+BT+" -> importa solo algo","",
"**Modulos de Python (ya vienen instalados):**","",
"| Modulo | Descripcion |",
"|--------|-------------|",
"| "+BT+"math"+BT+" | Funciones matematicas |",
"| "+BT+"random"+BT+" | Numeros aleatorios |",
"| "+BT+"os"+BT+" | Interactuar con el sistema operativo |",
"| "+BT+"json"+BT+" | Leer/escribir JSON |",
"| "+BT+"datetime"+BT+" | Fechas y horas |","",
"**Modulos externos (instalar con "+BT+"pip"+BT+"):**","",
"| Modulo | Descripcion |",
"|--------|-------------|",
"| "+BT+"requests"+BT+" | Hacer peticiones HTTP |",
"| "+BT+"pandas"+BT+" | Analisis de datos |",
"| "+BT+"numpy"+BT+" | Calculo numerico |",
])
cd[20] = NL.join([
"---","",
"## Ejercicio 5 de 9: Lectura de archivos","",
"> **Conceptos clave:** "+BT+"open()"+BT+", "+BT+"with"+BT+", "+BT+".strip()"+BT+", modos de archivo","",
"Crea un archivo de texto llamado "+BT+"mi_lista.txt"+BT+" con algunas palabras (una por linea). Luego:",
"1. Abre el archivo con "+BT+"open()"+BT+" y "+BT+"with"+BT,
"2. Lee cada linea",
"3. Guarda las palabras en una lista (usa "+BT+".strip()"+BT+" para quitar saltos de linea)",
"4. Imprime la lista","",
"> **Tip:**",
"> "+BT3+"python",
"> with open("archivo.txt", encoding="utf-8") as f:",
">     for linea in f:",
">         palabra = linea.strip()",
"> "+BT3,"",
"### Tu turno",
])
cd[24] = NL.join([
"---","",
"## Ejercicio 6 de 9: Modulo requests - API publica","",
"> **Conceptos clave:** "+BT+"requests.get()"+BT+", "+BT+".json()"+BT+", "+BT+"try/except"+BT+", APIs REST","",
"Haz una peticion GET a: "+BT+"https://api.agify.io?name=sofia"+BT+"  ",
"Esta API predice la edad segun el nombre.","",
"1. Importa "+BT+"requests"+BT+" ("+BT+"pip install requests"+BT+" si no lo tienes)",
"2. Haz "+BT+"requests.get(url)"+BT,
"3. Convierte la respuesta a JSON con "+BT+".json()"+BT,
"4. Imprime: nombre, edad estimada, numero de registros",
"5. Si hay error de conexion, imprime un mensaje","",
"> **Ojo:** Necesitas conexion a internet para este ejercicio.","",
"### Tu turno",
])
